# Makefile para mlab0-ex04-preenchimento_matriz.c

CC = gcc
CFLAGS = -Wall -pthread
TARGET = mlab0-ex04-preenchimento_matriz
SRC = mlab0-ex04-preenchimento_matriz.c

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)
